{
 "title": "Text Summarization Service Performance",
 "tags": [
  "mlops",
  "prometheus",
  "text-summarizer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Service Status & Health Check", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Target Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "up{job=\"summarization_service\"}"
    }
   ]
  },
  {
   "title": "Total Requests Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "sum(summarization_service_requests_total)"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(summarization_service_request_latency_seconds_sum[5m]) / rate(summarization_service_request_latency_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Request Rate (per sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(summarization_service_requests_total[5m]))"
    }
   ]
  },
  { "title": "Performance Graphs", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Request Latency Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(summarization_service_request_latency_seconds_sum[1m]) / rate(summarization_service_request_latency_seconds_count[1m])",
     "legendFormat": "Avg Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(summarization_service_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 Latency"
    }
   ]
  },
  {
   "title": "Request Rate by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(summarization_service_requests_total[1m])) by (status)",
     "legendFormat": "{{status}} status code"
    }
   ]
  },
  { "title": "Token Distributions", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Input Token Length Cumulative Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(summarization_service_input_token_length_bucket[10m])) by (le)",
     "legendFormat": "Input Token Length <= {{le}}"
    }
   ]
  },
  {
   "title": "Output Token Length Cumulative Histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(summarization_service_output_token_length_bucket[10m])) by (le)",
     "legendFormat": "Output Token Length <= {{le}}"
    }
   ]
  }
 ]
}